# **Numpy Homework**

Import numpy

Create an array of 10 zeros (Креирај низа од 10 нули)

Create an array of 10 ones (Креирај низа од 10 единици)

Create an array of 10 fives (Креирај низа од 10 петки)

In [ ]:
#nacin 1

In [ ]:
#nacin 2

Create an array of the integers from 10 to 50 (Креирај низа со цели броеви од 10 до 50)

Create an array of all the even integers from 10 to 50 (Креирај низа со цели парни броеви од 10 до 50)

Create a 3x3 matrix with values ranging from 0 to 8 (Креирај 3x3 матрица со вредности од 0 до 8)

In [ ]:
#nacin 1

In [ ]:
#nacin 2

Create a 3x3 identity matrix (Креирај 3x3 матрица на идентитет)

Use NumPy to generate a random number between 0 and 1 (Со помош на numpy генерирај рандом број помеѓу 0 и 1)

Use NumPy to generate an array of 25 random numbers (Со помош на numpy генерирај листа од 25 рандом броеви)

Create the following matrix: (Креирај ја следнава матрица)

In [ ]:
#pisuvajte go kodot vo ovaa kelija, za da ne go prebrisete resenieto vo slednata


[[50. 50. 50. 50. 50. 50.]
 [50. 50. 50. 50. 50. 50.]
 [50. 50. 50. 50. 50. 50.]
 [50. 50. 50. 50. 50. 50.]
 [50. 50. 50. 50. 50. 50.]
 [50. 50. 50. 50. 50. 50.]
 [50. 50. 50. 50. 50. 50.]
 [50. 50. 50. 50. 50. 50.]]


In [ ]:
#pisuvajte go kodot vo ovaa kelija, za da ne go prebrisete resenieto vo slednata


[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


Fill the missing values (Дополнете ги вредностите кои фалат)

In [ ]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

prv_element = ?????
print("\nPrv element:", prv_element)
vtor_element = ?????
print("Vtor element:", vtor_element)
tret_element = ?????
print("Tret element:", tret_element)
tret_element = ?????
print("Tret element od pozadi:", tret_element)
vtor_element = ?????
print("Vtor element od pozadi:", vtor_element)
prv_element = ?????
print("Prv element od pozadi:", prv_element)

In [ ]:
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

red1kolona1 = ?????
print("\nRed 1,Kolona 1:", red1kolona1)
red1kolona2 = ?????
print("Red 1,Kolona 2:", red1kolona2)
red2kolona1 = ?????
print("Red 2,Kolona 1:", red2kolona1)
red2kolona3 = ?????
print("Red 2,Kolona 3:", red2kolona3)
#istite baranja no so negativni indeksi
red1kolona1 = ?????
print("\nRed 1,Kolona 1:", red1kolona1)
red1kolona2 = ?????
print("Red 1,Kolona 2:", red1kolona2)
red2kolona1 = ?????
print("Red 2,Kolona 1:", red2kolona1)
red2kolona3 = ?????
print("Red 2,Kolona 3:", red2kolona3)

In [ ]:
x = np.arange(15)

print('Prvite 5 elementi se:', ????)
print('Poslednite 4 elementi se:', ????)
print('Prviot element e:', ????)
print("Posledniot element e:", ????)
print('Site elementi posle 3tiot se:', ????)
print('Subarray so elementite povegju 2 i 6 (so 6tiot):', ????)
print('Subarray so elementite povegju 2 i 6 (bez 6tiot):', ????)
print('Sekoj 2 element:', ????)
print('Sekoj 2 element pocnuvajki od 1:', ????)
print('Sekoj 3 element:', ????)
print('Elementite po obraten redosled:', ????)
print('Sekoj 2 element posle indeks 5 po obraten redosled:', ????)

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs: (Во следните неколку келии, ќе имате резултати од матрици, ќе треба да го напишете кодот за да ја добиете таа матрица)
Секаде ќе бидат оставени по 2 келии, пишувајте во првата за да не го пребришете резултатот од втората

1

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


Преку првата матрица пресметајте ги следните барања

1.1

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


1.2

20

1.3

[[ 2]
 [ 7]
 [12]]


1.4

[21 22 23 24 25]


1.5

[[16 17 18 19 20]
 [21 22 23 24 25]]


1.6 -> sum of all values (сума на сите елементи)

1.7 -> sum of all the columns (сума на сите колони)

2

[[ 5  7  9 11 13 15 17]
 [19 21 23 25 27 29 31]
 [33 35 37 39 41 43 45]
 [47 49 51 53 55 57 59]]


Преку првата матрица пресметајте ги следните барања

2.1

[[33 35 37 39 41]
 [47 49 51 53 55]]


2.2

[[15 17]
 [29 31]]


2.3

[19 21 23 25 27 29 31]


2.4 -> sum of all the rows (сума на сите редици)

2.5

59

1. Креирајте низа со 15 елементи.
2. Извадете ги првите 7 елементи.
3. Извадете ги последните 7 елементи.
4. Извадете ги елементите кои се наоѓаат помеѓу индексите 11 и 13 (со вклучен елементот на индекс 13)
5. Креирајте подниза која како елементи ќе го има секој 3 елемент од првичната низа.
6. Креирајте подниза која како елементи ќе го има секој 3 елемент од првичната нзиа, но по обратен редослед.
7. Креирајте низа со истите 15 елементи, но по обратен редослед.
8. Извадете ги елементите после елементот со индекс 7, но по обратен редослед.
9. Извадете ги елементите пред елементот со индекс 4, но по обратен редослед.
10. Извадете го секој 3 елемент после индекс 9, но по обратен редослед.


In [ ]:
#1

In [ ]:
#2

In [ ]:
#3

In [ ]:
#4

In [ ]:
#5

In [ ]:
#6

In [ ]:
#7

In [ ]:
#8

In [ ]:
#9

In [ ]:
#10

Креирај нова матрица чии елементи
ќе произлезат од други 2 матрици. Во прилог логиката која треба да ја искористите: (Ова е всушност множење на матрици)

In [ ]:
#c[0][0] = a[0][0]*b[0][0] + a[0][1]*b[1][0]
#c[0][1] = a[0][0]*b[0][1] + a[0][1]*b[1][1]
#c[1][0] = a[1][0]*b[0][0] + a[1][1]*b[1][0]
#c[1][1] = a[1][0]*b[0][1] + a[1][1]*b[1][1]

A
 [[2 3]
 [3 4]]
B
 [[1 1]
 [1 1]]
C
 [[5 5]
 [7 7]]


In [ ]:
#resenieto napisete go ovde
